### PR TITLE
Polygon pretty print

### PR DESCRIPTION
**Pull request by r-spiridonov**
We have some issue with polygon printing. For example when we set just 8 points then we have following result:
image
As you can see one point is missed. We expect something like:
image
So need to remove `-1` from the cycle

### CODE REVIEW

**Comment by r-spiridonov** [comment]
@w8r can you please review and approve the changes?

**Comment by r-spiridonov** [comment]
related to [this](https://github.com/w8r/L.Circle.toPolygon/issues/2) issue

**Comment by w8r** [comment]
Thanks a lot!

**Comment by r-spiridonov** [comment]
thanks Alex :)

**Pull request merged**
